// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4FPIBQGAEVHBBGbSKhY3myK1fIFug4h0',
    appId: '1:901485799632:web:41df8b0950359b5503d6d5',
    messagingSenderId: '901485799632',
    projectId: 'econowise-9a3b6',
    authDomain: 'econowise-9a3b6.firebaseapp.com',
    storageBucket: 'econowise-9a3b6.appspot.com',
    measurementId: 'G-7EK3GMLNWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ZmGeP7e0EYlm859CDkI1Vj_3YQtNPOw',
    appId: '1:901485799632:android:e8bca806cba130af03d6d5',
    messagingSenderId: '901485799632',
    projectId: 'econowise-9a3b6',
    storageBucket: 'econowise-9a3b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ177TF3cFaJj6-sTSwdU84PDW5dKF94s',
    appId: '1:901485799632:ios:2f835c71f9cb14f103d6d5',
    messagingSenderId: '901485799632',
    projectId: 'econowise-9a3b6',
    storageBucket: 'econowise-9a3b6.appspot.com',
    iosClientId: '901485799632-ua7424648lfqkbc09qkuaoicnfn42occ.apps.googleusercontent.com',
    iosBundleId: 'com.example.econowise',
  );

}